### ISSUE TITLE
TOC-Action triggert sich selbst

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-pi19-sem3#10]
Dadurch das die TOC-Action direkt auf `main` pusht wird die Action erneut von sich selbst getriggert. Da keine Änderungen erkannt werden, haben wir glücklicherweise keine Endlosschleife, aber kann man eventuell bestimmte commit messages o.ä. als Trigger ausschließen?

**Comment by RvNovae** [comment]
Vielleicht gehts ja mit dem access token jetzt auch auf der jeweiligen PR branch?
```yaml
on: pull_request
```
