### ISSUE TITLE
Last few workflow runs failed

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem3#113]
`! LaTeX Error: Cannot determine size of graphic in /tmp/tex2pdf.-ecb0fa93f63df8
81/2c1f40df6e0215a1560ffafe2d962c6be41c8056.shtml (no BoundingBox).`

See e.g.: https://github.com/importPI19fromDHGE/dhge-pi19-sem3/runs/1545586211

**Comment by ZeroPointMax** [comment]
Ist das vielleicht ein Folgefehler von den Quadrillionen Sachen darüber beginnend bei Logzeile 8028?

**Comment by RvNovae** [comment]
> Ist das vielleicht ein Folgefehler von den Quadrillionen Sachen darüber beginnend bei Logzeile 8028?

Natürlich gut möglich, habe es mir noch nicht so ganz genau angeschaut.

**Comment by photovoltex** [comment]
![image](https://user-images.githubusercontent.com/36958734/102202601-d0f40880-3ec7-11eb-8589-69421cd7ff97.png)
![image](https://user-images.githubusercontent.com/36958734/102202665-e9fcb980-3ec7-11eb-917e-32dba26915e2.png)

die beiden Links sollten nicht als Images definiert sein, dann sollte der build theoretisch durchlaufen :)

**Comment by ZeroPointMax** [comment]
![image](https://user-images.githubusercontent.com/26359277/102204854-a9eb0600-3eca-11eb-91f5-5197b8ee0ffc.png)

Dadum...

**Comment by photovoltex** [comment]
🥁
![image](https://user-images.githubusercontent.com/36958734/102205856-0b5fa480-3ecc-11eb-8628-b778ddc04a53.png)

statt 2200 (welches eine Bild war) war auf dem Bild das ich reingestellt habe Zeile 2029 (welches immer noch ein Bild ist aber ein Link sein sollte) zu sehen... 

_ja hätte man besser formatieren können😅_

**Comment by ZeroPointMax** [comment]
@photovoltex ups

**Comment by ZeroPointMax** [comment]
Hmm also wir suchen den Fehler [irgendwo hier](https://github.com/importPI19fromDHGE/dhge-pi19-sem3/commit/afed5d39000c4c6e03ff118f813366e98115ba23)

**Comment by ZeroPointMax** [comment]
Wenn @Steve2955 das lokal **ohne Theme** macht, kommt ein "too deeply nested"-Fehler, aber unser Theme hat genug Tiefe in den Listenpunkten, wie mir scheint
