### ISSUE TITLE
V-Modell Grafik fehlerhaft

### ISSUE THREAD

**Issue by B3n3d1c7** [importPI19fromDHGE/dhge-pi19-sem3#120]
Semester 3 / SWE-Kasche / V-Modell

Analyse <-im Fehlerfall-> Akzeptanz-Tests
High-Level-Design <-im Fehlerfall-> System-Tests
Low-Level-Design <-im Fehlerfall-> Integrations-Tests
Implementiertung <-im Fehlerfall-> Unit-Tests

**Comment by Steve2955** [comment]
Es geht um Folgende Grafik, richtig?

![](https://github.com/importPI19fromDHGE/dhge-pi19-sem3/blob/main/SWE-KASCHE/assets/v-modell.png?raw=true)

Was da definitv fehlt, ist das Low-Level-Design. Bei dem "im Fehlerfall" bin ich mir da noch nicht ganz so sicher. Hast du da vielleicht eine Skizze oder so, wie das gemeint ist? Man sollte doch eigentlich in jedem Fall testen, nicht nur im Fehlerfall.

**Comment by B3n3d1c7** [comment]
korrekt, es geht um die Grafik
ich habe das Bild gerade mal neu erstellt
man muss im Fehlerfall bei einer Stufe nicht komplett von vorne anfangen, sondern springt auf gleicher Ebene vom Test in die Entwicklung zurück

![V-Modell](https://user-images.githubusercontent.com/33860735/115831694-3cb82600-a412-11eb-9776-f488027d4815.png)

**Comment by Steve2955** [comment]
Okay, so mach das auf jeden Fall mehr Sinn. Die beidseitigen Pfeile in der ersten Darstellung haben mich etwas irritiert. 

Hier die angepasste Grafik:

![v-modell](https://user-images.githubusercontent.com/21085384/115837258-ac311400-a418-11eb-93ba-de44a97152d8.png)
