### ISSUE TITLE
PDF-Workflow failed

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-pi19-sem3#126]
Wenn ich das richtig gesehen habe, failed seit Commit 273e06560809f29b6ed6bd28ef1921f0376b7f8d (git blame @nukerxy) der PDF-Workflow mal wieder. Vielleicht hat jemand Motivation sich damit zu beschäftigen? 😅

**Comment by nukerxy** [comment]
natürlich ist es der mitten in der Nacht Commit... ich schaue es mir an

**Comment by nukerxy** [comment]
![image](https://user-images.githubusercontent.com/26322754/121855860-1ae16e00-ccf4-11eb-9511-06b03cf6b74e.png)
Hängt an der Tabelle bei V-Modell / am Bild dessen. Kein Plan tbh, meine Commits haben ja nur bissel Typos geändert

**Comment by ZeroPointMax** [comment]
*kopfkratz*

**Comment by ZeroPointMax** [comment]
Ich habe jetzt sowohl die Tabelle als auch das Bild gelöscht und und es [failed](https://github.com/ZeroPointMax/dhge-pi19-sem3/runs/2820652583?check_suite_focus=true) immer noch

**Comment by ZeroPointMax** [comment]
![image](https://user-images.githubusercontent.com/26359277/121908067-f1910400-cd2c-11eb-807c-c2108109d705.png)

Wenn man den LaTeX "Quellcode" extrahiert und an die failende Stelle springt, kommt man hier raus

**Comment by nukerxy** [comment]
Das Plus kann es aber nicht sein, oder?

**Comment by ZeroPointMax** [comment]
Ne, war es nicht :/

**Comment by ZeroPointMax** [comment]
![image](https://user-images.githubusercontent.com/26359277/122024959-379ba580-cdc9-11eb-8ef9-fefc4381453a.png)

Wenn man in meinen Fork schaut, failed es immer in Zeile 1031, was das erste Vorkommen (von 15) diesen Konstruktes ist... @RvNovae @photovoltex sieht das verdächtig aus?

**Comment by photovoltex** [comment]
`! Missing number, treated as zero.`
Scheint der selbe Fehler wie letztes mal zu sein... irgendwie kommt diese Konvertierung nicht vernünftig mit Tabellen zurecht oder?
Ihr könntet es einfach wieder umgehen anderweitig würde man sich da jetzt wahrscheinlich dumm und dämlich suchen und am Ende ist es ein Bug den man nicht fixen kann da es in der Action direkt hängt... aber nur meine Meinung wartet nochmal bis @RvNovae Feierabend hat ^^

**Comment by RvNovae** [comment]
Ah, mit so komplexeren Tabellen struggle ich auch immer ... 
Da fällt mir auf die Schnelle jetzt auch nichts ein

**Comment by ZeroPointMax** [comment]
> am Ende ist es ein Bug

hab ich auch gehofft und mal das Docker Image geforkt und sozusagen ein Update erzwungen, was ich dann in meinem sem3-Fork eingespielt habe. Immerhin kommt jetzt eine leicht veränderte Fehlersituation xD (also der LaTeX-Quelltext ist anders, aber es kommt immernoch zu einem Fehler)

**Comment by Steve2955** [comment]
[Läuft wieder](https://github.com/importPI19fromDHGE/dhge-pi19-sem3/actions/runs/953244488)

Neue Version vom Theme und in der einen Tabelle hat ihm noch was nicht gefallen 😅
