### ISSUE TITLE
WLAN-Verbindung in der Hochschule mit einem Linux-Laptop

### ISSUE THREAD

**Issue by MhouneyLH** [importPI19fromDHGE/dhge-pi19-sem3#132]
Hat jemand Erfahrung damit, wie man sich unter Linux mit dem Hochschul-WLAN verbinden kann? Ich verwende Fedora 36. Über die normale GUI funktioniert es jedoch leider nicht und auch die Tipps von Prof. Kusche mit dem Tool "wpa_supplicant" haben mir nicht geholfen.

**Comment by emkZero** [comment]
Hi. Das Hochschul-WLAN sollte auch auf Linux eigentlich ohne Weiteres mit NetworkManager funktionieren. Der wpa_supplicant-Trick ist mir nicht bekannt.
Fedora hat auch NetworkManager oder?

Sieht auf meinem Arch mit KDE wie folgt aus:

![image](https://user-images.githubusercontent.com/26359277/204110786-e64c800f-7ee2-4c9a-9bfd-3ab8a3cbc5eb.png)

Ich hatte mal ein Gespräch mit einem Admin (nenne ihn nicht beim Namen, weil öffentliche Convo und so) - der meinte, Broadcom Chips würden aus unbekannten Gründen gerne streiken und sich nicht mit den DHGE-APs verbinden wollen.

Hoffe es hilft und frohen ersten Advent morgen ^^

**Comment by MhouneyLH** [comment]
Danke für die schnelle Antwort. Ja, Fedora hat auch NetworkManager. Damit hatte ich es jedoch schon versucht und es sah genauso aus wie bei dir. Bin auch sämtliche Kombinationen von Benutzername und Passwort durchgegangen, nur um sicher zu gehen. xD

Trotzdem vielen Dank und dir auch noch einen frohen 1. Advent. 👍🏻

**Comment by MhouneyLH** [comment]
Okay, ich habe es heute gefixt bekommen. Ich vermute, dass es daran lag, dass ich bei dem Benutzername das "PI" von "######.PI21" nicht groß geschrieben hatte.

Ich verstehe zwar nicht genau, warum das überhaupt einen Unterschied macht, aber nun gut. Jetzt funktioniert es zumindest.

**Comment by emkZero** [comment]
Tja da kann man jetzt nur mutmaßen, warum [die Netzwerkfirma, dessen Name nicht genannt werden darf](https://www.cisco.com) das so implementiert hat.

Aber freut mich, dass es jetzt doch geht ^^
