### ISSUE TITLE
Repo Beschreibung

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem3#16]
Die derzeitige Beschreibung ist grammatisch etwas unschön. 😅
Die kann aber leider nur der owner updaten, deswegen mach ich das einfach mal als issue auf.

Mein Vorschlag wäre einfach ein paar mehr artikel zu verwenden:

```Mitschriften des Matrikel 2019, aus dem dritten Semester des Studiengangs "Praktische Informatik", an der DHGE```

![image](https://user-images.githubusercontent.com/11728465/95634609-91094300-0a8a-11eb-89eb-256f0d28ac20.png)

**Comment by Steve2955** [comment]
Danke für den Hinweis, zweimal lesen hätte nicht geschadet 😅
