### ISSUE TITLE
Die Playlist ist öffentlich

### ISSUE THREAD

**Issue by ZeroPointMax** [importPI19fromDHGE/dhge-pi19-sem3#24]
Zum Schutz von Herr Dorendorfs Material sind seine Videos öffentlich.
@Steve2955 deine Playlist ist zwar auch ungelistet, aber der Link ist öffentlich.

Ich habe dabei kein gutes Gefühl und glaube, Herr Dorendorf würde das auch nicht mögen...

Any thoughts?

**Comment by RvNovae** [comment]
Hmmm ja, wäre wahrscheinlich besser, wenn man den rausnimmt.

**Comment by Steve2955** [comment]
@RvNovae @Steve2955 Hat jemand von euch Erfahrung damit Infos komplett aus der git-history zu löschen? Weil selbst wenn wir das jetzt rausnehmen, ist es in den alten Commits immer noch drin 😅

**Comment by RvNovae** [comment]
> @RvNovae @Steve2955 Hat jemand von euch Erfahrung damit Infos komplett aus der git-history zu löschen? Weil selbst wenn wir das jetzt rausnehmen, ist es in den alten Commits immer noch drin 😅 

Hmm, da fiele mir maximal squashen ein, aber müsste man mal recherchieren. Geht bestimmt irgendwie...

**Comment by ZeroPointMax** [comment]
Ick hab dit ma mit nem Rebase gemacht... Aber kein Plan mehr wie das nochmal ging

**Comment by Steve2955** [comment]
Ich habe damals [`GFB`](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository) benutzt, kann mich aber auch daran erinnern einige Probleme damit gehabt zu haben.

**Comment by Steve2955** [comment]
Alternativ kann ich die Playlist natürlich auch einfach auf Privat stellen 😂

**Comment by Steve2955** [comment]
Playlist ist jetzt Privat
