### ISSUE TITLE
Bilder in PDFs

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem3#54]
Ist eigentlich schon jemandem aufgefallen, dass Bilder in den PDFs nicht auftauchen? Soll das so, oder geht das allgemein nicht 🤔

**Comment by ZeroPointMax** [comment]
Stimmt - Bilder wären was feines 😅

**Comment by Steve2955** [comment]
Du hast recht, wir sollten mal gucken welche Syntax und Pfade wir für die Bilder (wir haben ja teilweise Markdown-Syntax und teilweise HTML Tags verwendet) benutzen müssen damit es funktioniert. Pandoc unterstützt es definitiv.

**Comment by Steve2955** [comment]
Wenn man sich die Logs anguckt findet man nur folgende Zeilen bei der Umwandlung von DBS:

```
Warning:  Could not fetch resource './resources/erm-bsp.svg': replacing image with description
Warning:  Could not fetch resource 'resources/db_begriffe_screenshot.png': replacing image with description
```

Ich gucke mir das morgen nochmal genauer an

**Comment by Steve2955** [comment]
[Ich glaube ich weiß was das Problem ist.](https://github.com/jgm/pandoc/issues/3752)

**Comment by Steve2955** [comment]
Der zusätzliche Parameter hat tatsächlich geholfen. `pandoc` scheint weiterhin die HTML-Syntax nicht zu gefallen und zusätzlich gibt es jetzt ein Problem mit dem Font von Texten in SVGs 😅 

![image](https://user-images.githubusercontent.com/21085384/99362123-5e394280-28b3-11eb-8701-e16ea69afcb4.png)

**Comment by Steve2955** [comment]
@ZeroPointMax @RvNovae Was haltet ihr davon den Text in den SVGs einfach in Pfade umzuwandeln 😅

**Comment by Steve2955** [comment]
Alternativ könnten wir vielleicht noch

**Comment by Steve2955** [comment]
Was ich auch versucht habe ist die installierten Schriftarten im Container über `fc-list` auszugeben. Das ändern der Schriftart in der SVG auf eine der verfügbaren war allerdings nicht erfolgreich 🙄 

```
/usr/share/fonts/truetype/lato/Lato-Medium.ttf: Lato,Lato Medium:style=Medium,Regular
/usr/share/fonts/truetype/lato/Lato-SemiboldItalic.ttf: Lato,Lato Semibold:style=Semibold Italic,Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/truetype/lato/Lato-LightItalic.ttf: Lato,Lato Light:style=Light Italic,Italic
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
/usr/share/fonts/type1/gsfonts/n021024l.pfb: Nimbus Roman No9 L:style=Medium Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
/usr/share/fonts/truetype/lato/Lato-Italic.ttf: Lato:style=Italic
/usr/share/fonts/type1/gsfonts/n021004l.pfb: Nimbus Roman No9 L:style=Medium
/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
/usr/share/fonts/type1/gsfonts/p052023l.pfb: URW Palladio L:style=Italic
/usr/share/fonts/type1/gsfonts/n022003l.pfb: Nimbus Mono L:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
/usr/share/fonts/type1/gsfonts/z003034l.pfb: URW Chancery L:style=Medium Italic
/usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
/usr/share/fonts/truetype/lato/Lato-MediumItalic.ttf: Lato,Lato Medium:style=Medium Italic,Italic
/usr/share/fonts/type1/gsfonts/c059013l.pfb: Century Schoolbook L:style=Roman
/usr/share/fonts/truetype/lato/Lato-Black.ttf: Lato,Lato Black:style=Black,Regular
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
/usr/share/fonts/type1/gsfonts/d050000l.pfb: Dingbats:style=Regular
/usr/share/fonts/type1/gsfonts/n021023l.pfb: Nimbus Roman No9 L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/n019063l.pfb: Nimbus Sans L:style=Regular Condensed Italic
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
/usr/share/fonts/type1/gsfonts/a010013l.pfb: URW Gothic L:style=Book
/usr/share/fonts/truetype/lato/Lato-Light.ttf: Lato,Lato Light:style=Light,Regular
/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
/usr/share/fonts/truetype/lato/Lato-Regular.ttf: Lato:style=Regular
/usr/share/fonts/type1/gsfonts/n019064l.pfb: Nimbus Sans L:style=Bold Condensed Italic
/usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
/usr/share/fonts/type1/gsfonts/p052004l.pfb: URW Palladio L:style=Bold
/usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf: Lato,Lato Thin:style=Thin Italic,Italic
/usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
/usr/share/fonts/type1/gsfonts/n022023l.pfb: Nimbus Mono L:style=Regular Oblique
/usr/share/fonts/type1/gsfonts/a010015l.pfb: URW Gothic L:style=Demi
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/type1/gsfonts/n019043l.pfb: Nimbus Sans L:style=Regular Condensed
/usr/share/fonts/type1/gsfonts/n019044l.pfb: Nimbus Sans L:style=Bold Condensed
/usr/share/fonts/type1/gsfonts/a010033l.pfb: URW Gothic L:style=Book Oblique
/usr/share/fonts/type1/gsfonts/n021003l.pfb: Nimbus Roman No9 L:style=Regular
/usr/share/fonts/type1/gsfonts/s050000l.pfb: Standard Symbols L:style=Regular
/usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
/usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
/usr/share/fonts/type1/gsfonts/b018035l.pfb: URW Bookman L:style=Demi Bold Italic
/usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf: Lato,Lato Hairline:style=Hairline Italic,Italic
/usr/share/fonts/type1/gsfonts/c059033l.pfb: Century Schoolbook L:style=Italic
/usr/share/fonts/truetype/lato/Lato-Thin.ttf: Lato,Lato Thin:style=Thin,Regular
/usr/share/fonts/type1/gsfonts/a010035l.pfb: URW Gothic L:style=Demi Oblique
/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
/usr/share/fonts/truetype/lato/Lato-BoldItalic.ttf: Lato:style=Bold Italic
/usr/share/fonts/truetype/lato/Lato-Bold.ttf: Lato:style=Bold
/usr/share/fonts/type1/gsfonts/n019023l.pfb: Nimbus Sans L:style=Regular Italic
/usr/share/fonts/type1/gsfonts/b018012l.pfb: URW Bookman L:style=Light
/usr/share/fonts/truetype/noto/NotoMono-Regular.ttf: Noto Mono:style=Regular
/usr/share/fonts/type1/gsfonts/c059016l.pfb: Century Schoolbook L:style=Bold
/usr/share/fonts/type1/gsfonts/n022004l.pfb: Nimbus Mono L:style=Bold
/usr/share/fonts/type1/gsfonts/n019024l.pfb: Nimbus Sans L:style=Bold Italic
/usr/share/fonts/type1/gsfonts/b018032l.pfb: URW Bookman L:style=Light Italic
/usr/share/fonts/type1/gsfonts/p052003l.pfb: URW Palladio L:style=Roman
/usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
/usr/share/fonts/truetype/lato/Lato-Heavy.ttf: Lato,Lato Heavy:style=Heavy,Regular
/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
/usr/share/fonts/truetype/lato/Lato-Semibold.ttf: Lato,Lato Semibold:style=Semibold,Regular
/usr/share/fonts/type1/gsfonts/n019004l.pfb: Nimbus Sans L:style=Bold
/usr/share/fonts/type1/gsfonts/b018015l.pfb: URW Bookman L:style=Demi Bold
/usr/share/fonts/type1/gsfonts/n022024l.pfb: Nimbus Mono L:style=Bold Oblique
/usr/share/fonts/truetype/lato/Lato-HeavyItalic.ttf: Lato,Lato Heavy:style=Heavy Italic,Italic
/usr/share/fonts/type1/gsfonts/c059036l.pfb: Century Schoolbook L:style=Bold Italic
/usr/share/fonts/truetype/lato/Lato-BlackItalic.ttf: Lato,Lato Black:style=Black Italic,Italic
/usr/share/fonts/type1/gsfonts/p052024l.pfb: URW Palladio L:style=Bold Italic
/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
/usr/share/fonts/truetype/lato/Lato-Hairline.ttf: Lato,Lato Hairline:style=Hairline,Regular
/usr/share/fonts/type1/gsfonts/n019003l.pfb: Nimbus Sans L:style=Regular
```

**Comment by RvNovae** [comment]
> Alternativ könnten wir vielleicht noch die Bilder als Rastergrafik einfügen

Das wäre wahrscheinlich am einfachsten.

**Comment by RvNovae** [comment]
> Was ich auch versucht habe ist die installierten Schriftarten im Container über `fc-list` auszugeben. Das ändern der Schriftart in der SVG auf eine der verfügbaren war allerdings nicht erfolgreich 🙄
> 
> ```
> /usr/share/fonts/truetype/lato/Lato-Medium.ttf: Lato,Lato Medium:style=Medium,Regular
> /usr/share/fonts/truetype/lato/Lato-SemiboldItalic.ttf: Lato,Lato Semibold:style=Semibold Italic,Italic
> /usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf: DejaVu Serif:style=Bold
> /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
> /usr/share/fonts/truetype/lato/Lato-LightItalic.ttf: Lato,Lato Light:style=Light Italic,Italic
> /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Italic.ttf: Liberation Sans Narrow:style=Italic
> /usr/share/fonts/type1/gsfonts/n021024l.pfb: Nimbus Roman No9 L:style=Medium Italic
> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf: DejaVu Sans:style=Book
> /usr/share/fonts/truetype/lato/Lato-Italic.ttf: Lato:style=Italic
> /usr/share/fonts/type1/gsfonts/n021004l.pfb: Nimbus Roman No9 L:style=Medium
> /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf: Liberation Sans:style=Regular
> /usr/share/fonts/type1/gsfonts/p052023l.pfb: URW Palladio L:style=Italic
> /usr/share/fonts/type1/gsfonts/n022003l.pfb: Nimbus Mono L:style=Regular
> /usr/share/fonts/truetype/liberation/LiberationMono-BoldItalic.ttf: Liberation Mono:style=Bold Italic
> /usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf: Liberation Serif:style=Italic
> /usr/share/fonts/type1/gsfonts/z003034l.pfb: URW Chancery L:style=Medium Italic
> /usr/share/fonts/truetype/liberation/LiberationMono-Bold.ttf: Liberation Mono:style=Bold
> /usr/share/fonts/truetype/lato/Lato-MediumItalic.ttf: Lato,Lato Medium:style=Medium Italic,Italic
> /usr/share/fonts/type1/gsfonts/c059013l.pfb: Century Schoolbook L:style=Roman
> /usr/share/fonts/truetype/lato/Lato-Black.ttf: Lato,Lato Black:style=Black,Regular
> /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Regular.ttf: Liberation Sans Narrow:style=Regular
> /usr/share/fonts/type1/gsfonts/d050000l.pfb: Dingbats:style=Regular
> /usr/share/fonts/type1/gsfonts/n021023l.pfb: Nimbus Roman No9 L:style=Regular Italic
> /usr/share/fonts/type1/gsfonts/n019063l.pfb: Nimbus Sans L:style=Regular Condensed Italic
> /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf: DejaVu Sans:style=Bold
> /usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf: Liberation Serif:style=Bold
> /usr/share/fonts/type1/gsfonts/a010013l.pfb: URW Gothic L:style=Book
> /usr/share/fonts/truetype/lato/Lato-Light.ttf: Lato,Lato Light:style=Light,Regular
> /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf: Liberation Mono:style=Regular
> /usr/share/fonts/truetype/lato/Lato-Regular.ttf: Lato:style=Regular
> /usr/share/fonts/type1/gsfonts/n019064l.pfb: Nimbus Sans L:style=Bold Condensed Italic
> /usr/share/fonts/truetype/liberation/LiberationSans-Italic.ttf: Liberation Sans:style=Italic
> /usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf: Droid Sans Fallback:style=Regular
> /usr/share/fonts/type1/gsfonts/p052004l.pfb: URW Palladio L:style=Bold
> /usr/share/fonts/truetype/lato/Lato-ThinItalic.ttf: Lato,Lato Thin:style=Thin Italic,Italic
> /usr/share/fonts/truetype/liberation/LiberationSerif-BoldItalic.ttf: Liberation Serif:style=Bold Italic
> /usr/share/fonts/type1/gsfonts/n022023l.pfb: Nimbus Mono L:style=Regular Oblique
> /usr/share/fonts/type1/gsfonts/a010015l.pfb: URW Gothic L:style=Demi
> /usr/share/fonts/truetype/liberation/LiberationSansNarrow-BoldItalic.ttf: Liberation Sans Narrow:style=Bold Italic
> /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
> /usr/share/fonts/type1/gsfonts/n019043l.pfb: Nimbus Sans L:style=Regular Condensed
> /usr/share/fonts/type1/gsfonts/n019044l.pfb: Nimbus Sans L:style=Bold Condensed
> /usr/share/fonts/type1/gsfonts/a010033l.pfb: URW Gothic L:style=Book Oblique
> /usr/share/fonts/type1/gsfonts/n021003l.pfb: Nimbus Roman No9 L:style=Regular
> /usr/share/fonts/type1/gsfonts/s050000l.pfb: Standard Symbols L:style=Regular
> /usr/share/fonts/truetype/liberation/LiberationMono-Italic.ttf: Liberation Mono:style=Italic
> /usr/share/fonts/truetype/liberation/LiberationSans-BoldItalic.ttf: Liberation Sans:style=Bold Italic
> /usr/share/fonts/type1/gsfonts/b018035l.pfb: URW Bookman L:style=Demi Bold Italic
> /usr/share/fonts/truetype/lato/Lato-HairlineItalic.ttf: Lato,Lato Hairline:style=Hairline Italic,Italic
> /usr/share/fonts/type1/gsfonts/c059033l.pfb: Century Schoolbook L:style=Italic
> /usr/share/fonts/truetype/lato/Lato-Thin.ttf: Lato,Lato Thin:style=Thin,Regular
> /usr/share/fonts/type1/gsfonts/a010035l.pfb: URW Gothic L:style=Demi Oblique
> /usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf: Liberation Serif:style=Regular
> /usr/share/fonts/truetype/lato/Lato-BoldItalic.ttf: Lato:style=Bold Italic
> /usr/share/fonts/truetype/lato/Lato-Bold.ttf: Lato:style=Bold
> /usr/share/fonts/type1/gsfonts/n019023l.pfb: Nimbus Sans L:style=Regular Italic
> /usr/share/fonts/type1/gsfonts/b018012l.pfb: URW Bookman L:style=Light
> /usr/share/fonts/truetype/noto/NotoMono-Regular.ttf: Noto Mono:style=Regular
> /usr/share/fonts/type1/gsfonts/c059016l.pfb: Century Schoolbook L:style=Bold
> /usr/share/fonts/type1/gsfonts/n022004l.pfb: Nimbus Mono L:style=Bold
> /usr/share/fonts/type1/gsfonts/n019024l.pfb: Nimbus Sans L:style=Bold Italic
> /usr/share/fonts/type1/gsfonts/b018032l.pfb: URW Bookman L:style=Light Italic
> /usr/share/fonts/type1/gsfonts/p052003l.pfb: URW Palladio L:style=Roman
> /usr/share/fonts/truetype/liberation/LiberationSansNarrow-Bold.ttf: Liberation Sans Narrow:style=Bold
> /usr/share/fonts/truetype/lato/Lato-Heavy.ttf: Lato,Lato Heavy:style=Heavy,Regular
> /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf: Liberation Sans:style=Bold
> /usr/share/fonts/truetype/lato/Lato-Semibold.ttf: Lato,Lato Semibold:style=Semibold,Regular
> /usr/share/fonts/type1/gsfonts/n019004l.pfb: Nimbus Sans L:style=Bold
> /usr/share/fonts/type1/gsfonts/b018015l.pfb: URW Bookman L:style=Demi Bold
> /usr/share/fonts/type1/gsfonts/n022024l.pfb: Nimbus Mono L:style=Bold Oblique
> /usr/share/fonts/truetype/lato/Lato-HeavyItalic.ttf: Lato,Lato Heavy:style=Heavy Italic,Italic
> /usr/share/fonts/type1/gsfonts/c059036l.pfb: Century Schoolbook L:style=Bold Italic
> /usr/share/fonts/truetype/lato/Lato-BlackItalic.ttf: Lato,Lato Black:style=Black Italic,Italic
> /usr/share/fonts/type1/gsfonts/p052024l.pfb: URW Palladio L:style=Bold Italic
> /usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf: DejaVu Serif:style=Book
> /usr/share/fonts/truetype/lato/Lato-Hairline.ttf: Lato,Lato Hairline:style=Hairline,Regular
> /usr/share/fonts/type1/gsfonts/n019003l.pfb: Nimbus Sans L:style=Regular
> ```

Da kann man wahrscheinlich lange raten, bis man die richtige font gefunden hat 😅

**Comment by ZeroPointMax** [comment]
Ah, alles Mist. Meine Intention mit den SVGs war, dass es mitskaliert und immer schön scharf ist.
Too bad 😅 
Von einem Kollegen kenne ich, dass Fonts zur Hölle werden können.

TLDR: ich halte SVG -> PNG auch für sinnvoll.

Bzgl. HTML-Syntax: im MD Syntax kann man anscheinend nicht die Größe festlegen. Das war bei irgendeinem Bild aber notwendig, deshalb der Stilbruch auf meiner Seite.
Ich würde vorschlagen, mit PNGs den MD Syntax zu verwenden.

**Comment by ZeroPointMax** [comment]
@Steve2955 du hast { width = xyz } an die Bilder geschrieben - das wird bei mir im Chrome ignoriert und mit angezeigt. Mehr dazu im PR

**Comment by ZeroPointMax** [comment]
Fortschritt:

Yannis hat einen awk-Befehl gemacht, der Kommentare nach Bildern durchsucht und einen Kommentar dahinter löscht und den Inhalt des Kommentares mit geschweiften Klammern kapselt: https://github.com/importPI19fromDHGE/dhge-pi19-sem3/pull/56#issuecomment-731405157

Einen Bug hat der Befehl: auskommentierte Bilder werden auch in geschw. Klammern gekapselt

**Comment by Steve2955** [comment]
Wenn wir einmal dabei sind, sollten wir auch gleich pagebreaks unterstützen? Also z.B. `<!--pagebreak-->` wird zu `\pagebreak`.

```bash
awk '/!\[/{gsub(/<!--/,"{");gsub(/-->/,"}")};gsub("<!--pagebreak-->","\pagebreak");{print}'
```

Wenn ihr `awk` mal schnell testen wollt, ist hier ein gutes [Tool](https://awk.js.org/).

**Comment by Steve2955** [comment]
@ZeroPointMax Hast du dich nochmal mit dem Issue beschäftigt oder soll ich das übernehmen?

**Comment by ZeroPointMax** [comment]
ich bin gerade dabei, das in eine Action zu verpacken

**Comment by Steve2955** [comment]
@ZeroPointMax @RvNovae Bilder funktionieren, die `pagebreaks` leider nicht 😅

**Comment by RvNovae** [comment]
> @ZeroPointMax @RvNovae Bilder funktionieren, die `pagebreaks` leider nicht 😅

na immerhin 😉

**Comment by ZeroPointMax** [comment]
Bilder sind erledigt, Pagebreaks in einem eigenen Issue --> hier sind wir fertig, meine ich mal :)
