### ISSUE TITLE
TOC funktioniert nicht so, wie wir das gerne hätten

### ISSUE THREAD

**Issue by ZeroPointMax** [importPI19fromDHGE/dhge-pi19-sem3#7]
Damit wir nicht über 100 PRs irgendwas breitschmeißen und niemand mehr Überblick hat, ist das doch eines Issues würdig :-)

**Comment by RvNovae** [comment]
Oh ja, gute idee haha.
Hatte gehoft, dass das etwas einfacher geht. 😅

**Comment by ZeroPointMax** [comment]
Hier fliegt was auf die Nase:
```
RequestError [HttpError]: Validation Failed: {"resource":"PullRequest","field":"head","code":"invalid"}
```

Status-Code: 422 Unprocessable Entity
