### ISSUE TITLE
Pagebreaks funktionieren nicht, Newpage implementieren

### ISSUE THREAD

**Issue by ZeroPointMax** [importPI19fromDHGE/dhge-pi19-sem3#71]
Ein Folgeproblem aus #54 bzw. #70 

Der Ordnung halber kriegt das sein eigenes Issue :)

**Comment by Steve2955** [comment]
Btw, wenn wir einmal dabei sind, sollten wir `newpage` auch unterstützen.

**Comment by ZeroPointMax** [comment]
> Btw, wenn wir einmal dabei sind, sollten wir `newpage` auch unterstützen.

ah, sehr interessanter Unterschied zwischen den beiden. I mean, why not

**Comment by Steve2955** [comment]
Der Hauptfehler ist erstmal, dass der  backslash escaped werden muss. Das lässt sich ohne Probleme fixen, aber `pagebreak`, `newpage` und `clearpage` verhalten sich für mich aus irgendeinem Grund trotzdem noch nicht logisch. 

Ich würde gern nach dem TOC auf einer neuen Seite beginnen:

```markdown
TOC
\newpage
CONTENT
```

Das funktioniert aber aus irgendeinem Grund nicht. Wenn ich nun aber folgendes mache, dann steht die Überschrift alleine auf einer Seite.

 ```markdown
TOC
\newpage
#I AM ALONE ON THIS PAGE
\newpage
CONTENT
```

Ich habe das ganze auch schon mit `pagebreak` und `clearpage` versucht, aber ich konnte keine nachvollziehbaren Ergebnisse erzielen. Weiß nicht, ob ich mich dabei vielleicht nur blöd anstelle 😅
