### ISSUE TITLE
Markdown-Erweiterungen dokumentieren

### ISSUE THREAD

**Issue by Steve2955** [importPI19fromDHGE/dhge-pi19-sem3#72]

**Comment by ZeroPointMax** [comment]
Ich stelle hier nochmal zur Diskussion:

wie wollen wir das eigentlich machen? Ich sehe folgende Optionen:

- an die oberste Readme packen
- in eine eigene MD packen
- Wiki erstellen

mir persönlich ist es Wurst, Yannis hat Option 1 vorgeschlagen. Nur um den anderen nochmal die Möglichkeit zur Diskussion zu geben :)

**Comment by ZeroPointMax** [comment]
@B3n3d1c7 @LuisSchaefer @nukerxy @photovoltex @RvNovae @sthinbetween

**Comment by RvNovae** [comment]
Mir eigentlich auch relativ egal 😄
