### ISSUE TITLE
Namenskollisionen

### ISSUE THREAD

**Issue by ZeroPointMax** [importPI19fromDHGE/dhge-pi19-sem3#84]
Wir haben - aus der Linux-Welt geerbt - Namenskollisionen zwischen Dateien auf Windows. Linux ist ja case-sensitive, aber Windows nicht.

Beispiel: NET/resources/L2-net.png bzw. l2-net.png.

Wie wollen wir damit umgehen?

**Comment by Steve2955** [comment]
Uppercase muss weg, ich habe die Dateien eigentlich nur lowercase umbenannt, weiß nicht warum die `uppercase` jetzt immer noch da ist 😅

**Comment by Steve2955** [comment]
@ZeroPointMax Commit 30279662b43a680a99483da8eaf8808101e39f22 sollte das Ganze behoben haben 👍

**Comment by ZeroPointMax** [comment]
@Steve2955 bestätigt, danke 👍
