### ISSUE TITLE
Fehlende Resource in NET

### ISSUE THREAD

**Issue by RvNovae** [importPI19fromDHGE/dhge-pi19-sem3#99]
![image](https://user-images.githubusercontent.com/11728465/101281129-b3d77f80-37cd-11eb-85fc-d6192498f802.png)

Anscheinend wird hier ein `sockets.png` referenziert. Im Resources Ordner konnte ich leider nichts passendes finden. 

Ist anscheinend in diesem commit rausgeflogen: https://github.com/importPI19fromDHGE/dhge-pi19-sem3/pull/94/commits/30279662b43a680a99483da8eaf8808101e39f22

**Comment by ZeroPointMax** [comment]
ich würde mir mal git-Kunstwerke sparen und das Bild manuell zurück ins Leben holen

**Comment by ZeroPointMax** [comment]
![image](https://user-images.githubusercontent.com/26359277/101288085-e183ef00-37f4-11eb-95be-c0ece8aedb0b.png)

wahrscheinlich ein Versehen von @Steve2955
